### ISSUE TITLE
Bulk edit of categories in not working in Craft 3.3.8

### ISSUE THREAD

**Issue by bseigel** [venveo/craft-bulkedit#13]
I go through the steps, but categories are not getting updated.

**Comment by Mosnar** [comment]
Just tested this out on Craft 3.3.8 and didn't have any trouble editing categories. 

Could you provide some additional information:
- Field type you're trying to edit
- Field type translation settings (if applicable)
- Multi-site mode?
- Additional plugins active

**Comment by bseigel** [comment]
I tried again and I think it's working - likely something else was interfering. Thanks.
