### ISSUE TITLE
No Associated Fields error

### ISSUE THREAD

**Issue by jdsimcoe** [venveo/craft-bulkedit#22]
`Craft Version 3.4.8`
`BulkEdit Version 2.0.2.1`

Since upgrading BulkEdit I get this error when trying to edit Entries:

```
These elements have no associated fields.
```

I've never encountered this bug editing these entry types before, is there something I am missing? Thanks!

**Comment by Mosnar** [comment]
Hey @jdsimcoe - just curious, are you editing entries in the "All Entries" screen or are you clicked into a particular section? If you're in the "All Entries", could you try clicking into a particular section?

**Comment by jdsimcoe** [comment]
Hey @Mosnar I'm actually getting this error when clicked into a section called `Teachings`:

![image](https://user-images.githubusercontent.com/275617/75183191-d5f88900-56f6-11ea-9ef2-84500a29a487.png)

**Comment by Mosnar** [comment]
Okay, I think I figured out what's going on. It has to do with a scenario where all of the fields were deleted off of the entry type and then new fields were added.

I fixed a bug in the last release where fields that were deleted from an entry type could still show up on the bulk edit screen, but it appears that my solution caused this bug. I'll get a fix out ASAP!

**Comment by jdsimcoe** [comment]
Awesome, thanks @Mosnar!

**Comment by Mosnar** [comment]
@jdsimcoe Just released 2.0.3 that should fix this. Please let me know once you've verified it works!

**Comment by jdsimcoe** [comment]
@Mosnar just updated and BulkEdit is working again! Thanks for the quick turnaround.
