### ISSUE TITLE
"These elements have no associated fields."

### ISSUE THREAD

**Issue by ryanwhitney** [venveo/craft-bulkedit#24]
I'm looking to bulk edit fields on assets within my Craft (3.4.8) site. 

All of the assets within one Volume have the same extra fields: a lightswitch and a toggle.

When I go to bulk edit them, I get a "These elements have no associated fields." error. 

Is there any extra work to make them "associated"? They have identical fields (all blank/in the same state) at the moment.

**Comment by Mosnar** [comment]
Sorry about the trouble! It should just work without configuration - let me give it a look!

**Comment by Mosnar** [comment]
Fixed in 2.0.4
