### ISSUE TITLE
Bulk Edit not available in the actions menu due to permissions check

### ISSUE THREAD

**Issue by heymarkreeves** [venveo/craft-bulkedit#37]
Using both an admin user and a non-admin with all permissions enabled, and verifying the Bulk Edit permissions are set in the database, I do not see Bulk Edit in the actions menu unless I comment out [the permissions check](https://github.com/venveo/craft-bulkedit/blob/4bda93acb80b7e2f1b91ee0bcedc68b95f6d4fad/src/Plugin.php#L89).

**Comment by Mosnar** [comment]
Sorry, I wasn't able to reproduce this issue. I would suggest trying again with the latest version of Craft - perhaps there was a bug within Craft itself at some point? If you're able to confirm this is still a problem, leaving some details about plugin version & Craft version would be helpful. 

Thanks!
