### ISSUE TITLE
Bulk edit on assets

### ISSUE THREAD

**Issue by lexislav** [venveo/craft-bulkedit#4]
Do You have any plans to adjust this awesome plugin for the assets?
Bulk edit of images titles etc. would be really useful!

**Comment by Mosnar** [comment]
Could you elaborate on the functionality you're looking for here? Are you wanting to be able to simply mass-assign fields on assets?

**Comment by lexislav** [comment]
Exactly. The ability to mass-assign values to fields on asset's volumes would be very useful. For example on photos volume, I would love to mass-assign title and location fields.

Your plugin does this, but only for entries. I have no idea if that is a huge difference.

**Comment by Mosnar** [comment]
Gotcha. Okay, I think we can work this in.

**Comment by blacksaltstudio** [comment]
I am really hoping for this feature. For me this would be a big time saver. 

As an example, on my assets I have the following fields

- Title
- Description
- Athlete (entries field)
- Photographer (entries field)
- Event (entries Field)
- Visability (Checkboxes (Public, Media)

Going into each image and setting this data is a slow process considering in a gallery of 60 photos, there are usually 50% for one event and 50% for another and spread across 2 photographers. The ability to select a group of assets and apply the correct photographer and event in one go would be amazing.

**Comment by Mosnar** [comment]
Sorry for the delays on this, but I wanted to provide an update here. I've started a new major release currently on the `develop` branch that adds support for bulk editing fields on Assets, Users, and Categories. 

There are a few more things to clean up and test before it's released, but I expect this to be released as v2.0.0 fairly soon.

**Comment by Mosnar** [comment]
Just released v1.1.0 with asset support

**Comment by lexislav** [comment]
Great news! Thanks for a quite useful feature.
