### ISSUE TITLE
Craft 4?

### ISSUE THREAD

**Issue by angieherrera** [venveo/craft-bulkedit#40]
Wondering if this plugin will get updated for Craft 4?

**Comment by Mosnar** [comment]
Working on it! I've got it about 90% done, just waiting for some spare time to finish it up.

**Comment by zawilliams** [comment]
Sweet - this is one of the last plugins needing to be updated on my Craft install. Would love to update soon!

**Comment by Mosnar** [comment]
I'm still working on it - I promise! Just tough to juggle with my normal work.

**Comment by zawilliams** [comment]
Totally understandable. Thanks for your work on it!
