### ISSUE TITLE
Bulk edit Commerce products

### ISSUE THREAD

**Issue by j-greig** [venveo/craft-bulkedit#5]
Similar to https://github.com/venveo/craft-bulkedit/issues/4 but for Products in Craft Commerce - would be great if you could bulk assign values to category fields on products, for example.

**Comment by skoften** [comment]
Agree, important feature missing from the default Commerce plugin!

**Comment by Mosnar** [comment]
Just released v1.1.0 with Commerce product support

**Comment by j-greig** [comment]
Thank you!!! : )
