### ISSUE TITLE
Bulk Edit not work in latest Craft 4.5.6

### ISSUE THREAD

**Issue by azerozvn** [venveo/craft-bulkedit#55]
**Describe the bug**
I was updating from Craft 4.5.3 to 4.5.6 and it seems to blocking Bulk Edit menu to show up. 

**Environmental Info**
 - Craft CMS Version: 4.5.6
 - Multi-site Mode (Yes/No): Yes 
 - Plugin Version: 4.0.1
 - PHP Version: 8.1
 - Database Driver (MySQL/Postgres): MySQL

**Comment by adrianjean** [comment]
CraftCMS Core team seem to be working on a fix: https://github.com/craftcms/cms/commit/1a958a7c9e85568f060004e369ca8d02f020a105

**Comment by Mosnar** [comment]
Awesome, thanks for filing the bug report with them. Looks like they just released 4.5.6.1. Let me know if that doesn't resolve it!

**Comment by adrianjean** [comment]
Tested and CraftCMS 4.5.6.1 definitely fixes the issue.
