### ISSUE TITLE
Craft 5 Support

### ISSUE THREAD

**Issue by chasegiunta** [venveo/craft-bulkedit#56]
Just checking on if you plan to add support for Craft 5? Thank you

**Comment by tobystokes** [comment]
Given that Craft 5 supports 'Bulk inline editing', maybe not?

**Comment by Mosnar** [comment]
I started working on a Craft 5 update but it turned out to be less trivial than expected, so I'll have to come back to it when I have some free time. PRs welcome 😉

**Comment by SETU-WEB** [comment]
Really missing this plugin on craft5 , we need to bulk edit a lot and this saved so much time on craft4

**Comment by LinneaHarts** [comment]
Craft 5's current inline edit isn't really anything like this plugin. It just lets you edit some kinds of fields inline from the entry listing page, but not update a whole bunch of entries at once

**Comment by Mosnar** [comment]
Tagged 5.0.0-beta.1 - let me know if you have any issues. I did some testing and it seems to be working well, but I'd take backups just in case :)

**Comment by tobystokes** [comment]
Thanks @Mosnar !
I've just taken it for a spin for all the use cases I have for it, and it behaved admirably.
